AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Homework11 Part1

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC with Subnets covering 2 Availability zone at least.
    MinLength: 1

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select two private subnets covering 2 Availability zone at least.
    MinLength: 2

  KeyName:
    Type: String
    Default: mi-assignment17

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instances and MSK Cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 9092
        ToPort: 9198
        CidrIp: 0.0.0.0/0

  MSKClusterConfiguration:
    Type: AWS::MSK::Configuration
    Properties:
      Description: Configration for DE TRAINING MSK
      KafkaVersionsList:
      - "3.5.1"
      Name: MI-MSK-Conf
      ServerProperties: |
        auto.create.topics.enable=true
        default.replication.factor=2
        min.insync.replicas=2
        num.io.threads=8
        num.network.threads=5
        num.partitions=1
        num.replica.fetchers=2
        replica.lag.time.max.ms=30000
        socket.receive.buffer.bytes=102400
        socket.request.max.bytes=104857600
        socket.send.buffer.bytes=102400
        unclean.leader.election.enable=true
        zookeeper.session.timeout.ms=18000
        allow.everyone.if.no.acl.found=false

  MSKCloudWatchGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: mi-msk-logs

  MskCluster:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: MI-MSK-PART1
      BrokerNodeGroupInfo:
        InstanceType: kafka.t3.small
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: 20
        ClientSubnets: !Ref SubnetIds
        SecurityGroups:
        - !Ref EC2SecurityGroup
      KafkaVersion: "3.5.1"
      NumberOfBrokerNodes: 2
      EnhancedMonitoring: DEFAULT
      EncryptionInfo:
        EncryptionInTransit:
          ClientBroker: TLS
          InCluster: true
      ConfigurationInfo:
        Arn: !Ref MSKClusterConfiguration
        Revision: 1
      ClientAuthentication:
        Unauthenticated:
          Enabled: false
        Sasl:
          Iam:
            Enabled: true
          Scram:
            Enabled: true
      LoggingInfo:
        BrokerLogs:
          CloudWatchLogs:
            Enabled: true
            LogGroup: !Ref MSKCloudWatchGroup

Outputs:
  MskClusterArn:
    Description: MSK Cluster ARN
    Value: !Ref MskCluster
